version: '2'
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:management"
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  app:
    build: ./app
    environment:
      NODE_ENV: production
    restart: unless-stopped
    links:
      - redis
      - rabbitmq
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - redis
